#!/bin/sh
mkdir /etc/shadowvpn-newser


sername=XXXX
serport=10XXX
serpasswd=XXXXXX
intf=$sername
mtu=1432
net=10.7.X.1/24



cat > /root/$sername <<EOF
/usr/bin/shadowvpn -c /etc/shadowvpn-newser/$sername -s stop
echo 3333
sleep 3
/usr/bin/shadowvpn -c /etc/shadowvpn-newser/$sername -s start

EOF

chmod 777 /root/$sername



cat > /etc/shadowvpn-newser/$sername <<EOF
#server=::0
server=0.0.0.0
port=$serport
password=$serpasswd
intf=$intf
mtu=$mtu
net=$net

mode=server
concurrency=1
up=/etc/shadowvpn-newser/$sername.server_up.sh
down=/etc/shadowvpn-newser/$sername.server_down.sh
pidfile=/var/run/shadowvpn.$sername.pid
logfile=/var/log/shadowvpn.$sername.log
EOF


cat > /etc/shadowvpn-newser/$sername.server_up.sh <<EOF
#!/bin/sh

sysctl -w net.ipv4.ip_forward=1

ip addr add $net dev $intf
ip link set $intf mtu $mtu
ip link set $intf up

# turn on NAT over VPN
if !(iptables-save -t nat | grep -q "$sername"); then
  iptables -t nat -A POSTROUTING -s $net ! -d $net -m comment --comment "$sername" -j MASQUERADE
fi
iptables -A FORWARD -s $net -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -d $net -j ACCEPT

# Turn on MSS fix (MSS = MTU - TCP header - IP header)
#iptables -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

echo $(echo $)0 done
EOF


cat > /etc/shadowvpn-newser/$sername.server_down.sh <<EOF
#!/bin/sh

# Turn off NAT over VPN
iptables -t nat -D POSTROUTING -s $net ! -d $net -m comment --comment "$sername" -j MASQUERADE
iptables -D FORWARD -s $net -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -D FORWARD -d $net -j ACCEPT

# Turn off MSS fix (MSS = MTU - TCP header - IP header)
#iptables -t mangle -D FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

echo $(echo $)0 done

EOF



