#!/bin/sh
####iptables -F -t nat
mode=udp
#default=0.0.0.0/0
srcip=0.0.0.0/0

localip=XXXXXXXXX
localport=27777
remoteip=XXXXXXXXXX
remoteport=60661

/sbin/iptables -t nat -D PREROUTING -s  $srcip    -p  $mode --dport $localport  -j DNAT --to-destination  $remoteip:$remoteport &
sleep 1
/sbin/iptables -t nat -D POSTROUTING -p  $mode  -d  $remoteip --dport   $remoteport  -j SNAT --to-source  $localip &
sleep 1
echo finished del old iptables,wait 3s to add new one,or you can CTRL+C and make a new setting;
sleep 3

/sbin/iptables -t nat -I PREROUTING -s  $srcip    -p  $mode --dport $localport  -j DNAT --to-destination  $remoteip:$remoteport
/sbin/iptables -t nat -I POSTROUTING -p  $mode  -d  $remoteip --dport   $remoteport  -j SNAT --to-source  $localip

echo sucess
