#!/bin/sh
#
######startport must smaller than endport
localport_start=20300
localport___end=20399
######vpn lan remote ip
remoteip=10.0.202.1

#default=allip=0.0.0.0/0
srcip=0.0.0.0/0

######tcp or udp
mode=udp

######vpn lan local ip
varible=`/sbin/ip route|grep default | head -1` 
eth=`echo ${varible#*dev }|awk '{print $1}'      `

#if /sbin/ip route | grep $remoteip | head -1
#then
#varible=`/sbin/ip route|grep $remoteip` ; eth=`echo ${varible#*dev }|awk '{print $1}'      `
#fi

#eth=eth0
localip=`/sbin/ifconfig $eth | grep "inet addr:" |awk '{print $2}'| awk -F '[:]'  '{print $2}'    `

#localip=10.0.202.2



##########################################################

localport_rate=$localport_start:$localport___end
remoteport_rate=$localport_start-$localport___end

echo $localport_rate----$remoteport_rate

/sbin/iptables -t nat -D PREROUTING -s  $srcip    -p  $mode --dport $localport_rate  -j DNAT --to-destination  $remoteip:$remoteport_rate  &
sleep 1
/sbin/iptables  -t nat -D POSTROUTING -p  $mode  -d  $remoteip --dport   $localport_rate  -j SNAT --to-source  $localip   &
sleep 1

echo finished del old iptables,wait 3s to add new one,or you can CTRL+C and make a new setting;
sleep 3
/sbin/iptables  -t nat -I PREROUTING -s  $srcip    -p  $mode --dport $localport_rate  -j DNAT --to-destination  $remoteip:$remoteport_rate
/sbin/iptables  -t nat -I POSTROUTING -p  $mode  -d  $remoteip --dport   $localport_rate  -j SNAT --to-source  $localip







echo sucess
echo sucess
echo sucess
echo sucess
echo sucess

