#!/bin/sh
if [ -f "/tmp/checktiny1.ps_status_check.lock" ]
then
        exit 0
fi

##--------------------------------------------------------------------------------####
portt=1777
rip=8.8.8.8
rpo=53
tu="-u"
checktiny1=`ps x|grep "tinymappe007 -l 0.0.0.0:$portt "|grep -v "grep"`
if [ -z "$checktiny1" ]
then
  touch /tmp/checktiny1.ps_status_check.lock
  echo checktiny1.ps_RECONNECT port:$portt at: >> /tmp/checktiny1.ps_status_check.log
  date >> /tmp/checktiny1.ps_status_check.log
	
  sudo -u nobody -g nogroup tinymappe007 -l 0.0.0.0:$portt -r $rip:$rpo  $tu  >/dev/null &
  rm /tmp/checktiny1.ps_status_check.lock
fi
###########################################################################################


exit 0;## echo     */1 * * * * /root/ct
