#!/bin/sh
ls /tmp/checkct2_tmp2_lock && echo process going
ls /tmp/checkct2_tmp2_lock && exit 0
ssu=""
cat /etc/issue | grep untu && ssu="sudo -u nobody -g nogroup"
##local_port,remote_ip,remote_port,tu
tt0="
##61000,8.8.8.8,53,tu


"


sleep 5

###################
for iii in $tt0
do

if ! echo $iii | grep "#" 
then

lp=`echo $iii | awk -F '[,]' '{print $1}'`
rip=`echo $iii | awk -F '[,]' '{print $2}'`
rp=`echo $iii | awk -F '[,]' '{print $3}'`

tu="-u"
echo $iii | awk -F '[,]' '{print $4}' |grep t && tu="-t"
echo $iii | awk -F '[,]' '{print $4}' |grep u && tu="-u"
echo $iii | awk -F '[,]' '{print $4}' |grep tu && tu="-t -u"
echo $iii | awk -F '[,]' '{print $4}' |grep ut && tu="-t -u"

if ! ps x|grep -v grep | grep "tiny666 -l 0.0.0.0:$lp $tu -r $rip:$rp"
then

touch /tmp/checkct2_tmp2_lock

	if ps x|grep -v grep | grep "tiny666 -l 0.0.0.0:$lp -"
	then
		for jj in `ps x|grep -v grep | grep "tiny666 -l 0.0.0.0:$lp -" | awk '{print $1}' `
		do
			kill $jj
		done
	fi
	
	$ssu tiny666 -l 0.0.0.0:$lp $tu -r $rip:$rp  >/dev/null &

rm /tmp/checkct2_tmp2_lock

fi
fi

done
###################

echo ----------------------------------------
echo -------------------------
ps x|grep tiny666|grep -v grep




exit 0;

## echo     */1 * * * * /root/ct2
